#!/bin/bash

export PYTHONSTARTUP="$HOME/.pythonrc"
export WORKON_HOME="$HOME/codigo/envs"
export PIP_REQUIRE_VIRTUALENV=true
export PIP_RESPECT_VIRTUALENV=true
export PIP_VIRTUALENV_BASE=$WORKON_HOME
VENVW_PATH=$(which virtualenvwrapper.sh)
[ $? = 0 ] && source $VENVW_PATH

